// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJhHD8au47OqPrXu4ESICDK_ydlgLMMiw',
    appId: '1:609759148263:web:ecf0d0ec8c0e05f3aa0a42',
    messagingSenderId: '609759148263',
    projectId: 'projeto-viagens-e94b6',
    authDomain: 'projeto-viagens-e94b6.firebaseapp.com',
    storageBucket: 'projeto-viagens-e94b6.firebasestorage.app',
    measurementId: 'G-HB20HF3EFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlvtRUfHpEAyGEhjgzG9sPIdSUewVQn54',
    appId: '1:609759148263:android:53dada70e179fd7baa0a42',
    messagingSenderId: '609759148263',
    projectId: 'projeto-viagens-e94b6',
    storageBucket: 'projeto-viagens-e94b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGn_nyiTaeVRIRrpAVuMCWLY5HDicNZvo',
    appId: '1:609759148263:ios:b920e03e3773f635aa0a42',
    messagingSenderId: '609759148263',
    projectId: 'projeto-viagens-e94b6',
    storageBucket: 'projeto-viagens-e94b6.firebasestorage.app',
    iosBundleId: 'com.example.viagens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGn_nyiTaeVRIRrpAVuMCWLY5HDicNZvo',
    appId: '1:609759148263:ios:b920e03e3773f635aa0a42',
    messagingSenderId: '609759148263',
    projectId: 'projeto-viagens-e94b6',
    storageBucket: 'projeto-viagens-e94b6.firebasestorage.app',
    iosBundleId: 'com.example.viagens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJhHD8au47OqPrXu4ESICDK_ydlgLMMiw',
    appId: '1:609759148263:web:165c75cc0357551faa0a42',
    messagingSenderId: '609759148263',
    projectId: 'projeto-viagens-e94b6',
    authDomain: 'projeto-viagens-e94b6.firebaseapp.com',
    storageBucket: 'projeto-viagens-e94b6.firebasestorage.app',
    measurementId: 'G-QC9S409SJP',
  );
}
